apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: tzby79rx5-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-fa0cf7598f.haqa.p3.openshiftapps.com/rhtap/rhtap-qe:6c01f604fef082a0d72405c5e2dfe481357831e5@sha256:b151292f0a20817bcb417e7f1b9eb6705c052f9e9946f1ee8f129d6059f48fc0
        name: container-image  
